version: '3.8'

services:
  tofu-music-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tofu-music-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/songs.db:/app/songs.db
    environment:
      - FLASK_DEBUG=false
      # 可以在这里添加其他环境变量
      # - DATABASE_URL=postgresql://user:password@db:5432/dbname
    networks:
      - tofu-network

  # 如果需要数据库服务，可以取消下面的注释
  # db:
  #   image: postgres:14-alpine
  #   container_name: tofu-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=tofu_music
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - tofu-network

networks:
  tofu-network:
    driver: bridge

# 如果使用PostgreSQL，取消下面的注释
# volumes:
#   postgres_data: 